### ISSUE TITLE
Remove from multiple files ?

### ISSUE THREAD

**Issue by andyscott12** [ehynds/grunt-remove-logging#12]
Hi Guys,

Bit confused how to run this out for a whole directory of files ?

```
removelogging: {
    dist: {
      src: './build/**/*.js',
      dest: './build/**/*.js',
      options: {
        // see below for options. this is optional.
      }
    }
}
```

tried that but it didnt work ? How can I basically take all files in 1 directory, remove logging and then just overwrite the file again in that dir ?

**Comment by charliedowler** [comment]
I'm looking for a solution to this as well, can't seem to find a way.

**Comment by shakyShane** [comment]
Pull request submitted that provides exactly this functionality.

https://github.com/ehynds/grunt-remove-logging/pull/13

**Comment by charliedowler** [comment]
cheers :)

**Comment by alekseychikin** [comment]
@ehynds, can you confirm that pull request, update version and upload to npmjs.com? It would be very useful.

**Comment by ehynds** [comment]
#13 is merged.

**Comment by shakyShane** [comment]
:+1:

**Comment by alekseychikin** [comment]
And it doesn't work =)
I try:

```
removelogging: {
  main: {
    src: 'js/*.js'
  }
},
```

and get back:

```
Warning: Unable to write "undefined" file (Error code: undefined). Use --force to continue.
```

And this warning i've got everytime.
Also, at http://npmjs.org/package/grunt-remove-logging i see version 2.0, but at package.json is 0.1.1.

**Comment by ehynds** [comment]
Use `src: ['js/*.js']` instead, and I see 0.2.0 in the [package.json file](https://github.com/ehynds/grunt-remove-logging/blob/master/package.json#L4)?

**Comment by alekseychikin** [comment]
I installed it by

```
npm install grunt-remove-logging
```

And at node_modules/grunt-remove-loggin/package.json have:

```
...
  "name": "grunt-remove-logging",
  "description": "Grunt task to remove console logging statements",
  "version": "0.1.1",
  "homepage": "",
...
```

Maybe you forgot update at npm?

**Comment by ehynds** [comment]
0.2.0 is published on npm. try clearing your npm cache: `npm cache clean`

**Comment by alekseychikin** [comment]
Thanks! Sorry, my mistake.
