### ISSUE TITLE
Opinion : Look into using Esprima, Estraverse, and Escodegen

### ISSUE THREAD

**Issue by gfranko** [ehynds/grunt-remove-logging#19]
It might be cleaner to create and traverse an AST instead of using Regex's.  Just a thought!  Great job though =)

**Comment by ehynds** [comment]
Yep. I would actually recommend using [grunt-groundskeeper](https://github.com/Couto/groundskeeper) over this one, which was released after this plugin and leverages groundskeeper (which leverages esprima...).

**Comment by gfranko** [comment]
Nice, thanks!
