### ISSUE TITLE
Not Removing statements from Angular $log.debug

### ISSUE THREAD

**Issue by dreerr** [ehynds/grunt-remove-logging#25]
In my Grunt config I have [ 'console', 'console.log', 'window.console', '$log' , '\$log' , '$log.debug' , '\$log.debug' ]

but a statement like "$log.debug('display my debug message');" is not removed. How come?

**Comment by dreerr** [comment]
my bad sorry

**Comment by iamambrus** [comment]
could you comment on how to remove angular logging ($log.debug)? thanks

**Comment by ben-wall** [comment]
I would also like to know, please

**Comment by jmwohl** [comment]
In case anyone is still trying to do this — looking at the source, the namespaces are just concatenated as strings into the regex, so you need to escape the '$'. This is what worked for me to get rid of angular logs:

```
removelogging: {
  dist: {
    src: 'my/src.js',
    options: {
      namespace: ['\\$log'],
      replaceWith: '0;'
    }
  }
}
```
