### ISSUE TITLE
space between console.log and bracket

### ISSUE THREAD

**Issue by ghost** [ehynds/grunt-remove-logging#9]
Your plugin is brilliant but I have specific code. All call function have space between function/method name and bracket. Example:

console.log ('Lorem ipsum');

This code wasn't remove - I must remove space and then works. But I can't remove this because it is not compatible with code formatting for this project.

Could you fix this problem?

Thanks,
Aydao

**Comment by danvickers** [comment]
I'm also having this issue, a real shame as I keep forgetting the formatting required. Any fix or idea of work around would be a huge help.
